open-telemetry/opentelemetry-ruby-contrib

- instrumentation/aws_sdk/test/opentelemetry/instrumentation_test.rb
- instrumentation/delayed_job/test/opentelemetry/instrumentation/delayed_job_test.rb
- instrumentation/ruby_kafka/test/opentelemetry/instrumentation/ruby-kafka/instrumentation_test.rb
Looks like specs are failing for a few instrumentations on `main` when run against Ruby 3.1. Not sure why this started right now, but here's a shot at fixing it.
> Fixup tests against 3.1

- instrumentation/faraday/lib/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware.rb
- instrumentation/faraday/test/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware_test.rb
This is a copy of https://github.com/open-telemetry/opentelemetry-ruby/pull/1308
Some Ruby gems (e.g. [`elasticsearch-transport`](https://github.com/elastic/elastic-transport-ruby/blob/391ed956b23b9b3be3fd962f8fc5366e410006eb/lib/elastic/transport/transport/http/faraday.rb#L49-L54) use [`Faraday::Connection#run_request`](https://www.rubydoc.info/github/lostisland/faraday/Faraday%2FConnection:run_request) directly. This method accepts full URL along with the basic auth credentials as part of it.
As a result, credentials leak via `http.url` span attribute.
This PR modifies the specs to fail by using `run_request` and also fixes the code to "cleanse" the URL with the existing helper method.
<details>
<summary>How to reproduce</summary>
```ruby
gem 'faraday', '= 0.15.4'
gem …
```
> fix: Stop leaking basic authentication credentials in Faraday instrumentation

- CONTRIBUTING.md
This PR removes and updates some information thats not relevant to this repo after it was split from the general opentelemetry-ruby repo.
> Update CONTRIBUTING.md to remove opentelemetry-ruby specific information

- .github/workflows/ci.yml
- instrumentation/sidekiq/Rakefile
This PR starts to fix issues related to supporting TruffleRuby (added in https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/59) by fixing the Sidekiq implementation test issues.
This should fix https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/46
This commit fixes the following error from the Rakefile due to using `fork` for starting
redis:
```
NotImplementedError: fork is not available
```
According to the TruffleRuby compatibility docs, `fork` is not compatible in TruffleRuby:
> You cannot fork the TruffleRuby interpreter. The feature is unlikely to ever be supported when running on the JVM but could be supported in the future in the native configuration. 
After fixing that issue, I was able to successfully run a passing test suite for the Sidekiq …
> Fix: make sidekiq instrumentation rake task compatible with TruffleRuby

- instrumentation/aws_sdk/lib/opentelemetry/instrumentation/aws_sdk/messaging_helper.rb
- instrumentation/aws_sdk/test/opentelemetry/instrumentation_test.rb
> fix: suppress invalid span attribute value type warning in aws-sdk instrumentation

- .gitignore
- instrumentation/net_http/README.md
- instrumentation/net_http/lib/opentelemetry/instrumentation/net/http/instrumentation.rb
- instrumentation/net_http/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb
- instrumentation/net_http/test/opentelemetry/instrumentation/net/http/instrumentation_test.rb
Add support for `request_hook` and `response_hook` that allow adding user-customizable attributes to the span. This capability is common across http client instrumentations in other languages (see https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/opentelemetry-instrumentation-http and https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-urllib3 in node and python, respectively).
For example, this capability can be used to collect data from request/response headers.
> feat: add net http instrumentation hooks config

- instrumentation/faraday/README.md
- instrumentation/faraday/lib/opentelemetry/instrumentation/faraday/instrumentation.rb
- instrumentation/faraday/lib/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware.rb
- instrumentation/faraday/test/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware_test.rb
- instrumentation/http/README.md
- instrumentation/http/lib/opentelemetry/instrumentation/http/instrumentation.rb
- instrumentation/http/lib/opentelemetry/instrumentation/http/patches/client.rb
- instrumentation/http/test/instrumentation/http/patches/client_test.rb
- instrumentation/http_client/README.md
- instrumentation/http_client/lib/opentelemetry/instrumentation/http_client/instrumentation.rb
- instrumentation/http_client/lib/opentelemetry/instrumentation/http_client/patches/client.rb
- instrumentation/http_client/test/instrumentation/http_client/patches/client_test.rb
- instrumentation/restclient/README.md
- instrumentation/restclient/lib/opentelemetry/instrumentation/restclient/instrumentation.rb
- instrumentation/restclient/lib/opentelemetry/instrumentation/restclient/patches/request.rb
- instrumentation/restclient/test/opentelemetry/instrumentation/restclient/instrumentation_test.rb
Same as the case in https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/62 - align the functionality of all http clients.
> feat: add request/response hooks to more http clients

- CONTRIBUTING.md
- docker-compose.yml
- otelcol-config.yml
Mostly this is borrowed from open-telemetry/opentelemetry-demo-webstore.
This commit adds the opentelemetry-collector and the jaeger all-in-one
image to the docker-compose file. This allows us to export traces in
development to a collector and then visualize them in the Jaeger UI.
Fixes #74
> feat: Add simple opentelemetry-collector config for use in dev

- .github/workflows/ci.yml
We noticed when attempting to release a gem from this repo that the workflow to create release PRs [did not have the CI workflow run](https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/91/checks) on them. This ought to make CI run on release branches in this repo.
> ci: run CI on release branches

- .github/workflows/ci.yml
Followup to #92, turns out "release" in release branch names is not plural.
> ci: release is not plural in release branches

- CODEOWNERS
- README.md
Follow-up to [the conversation in CNCF Slack #otel-ruby](https://cloud-native.slack.com/archives/C01NWKKMKMY/p1657664615160479) and [the comment](https://github.com/open-telemetry/opentelemetry-ruby/pull/1342#pullrequestreview-1039111788) on the similar PR on otel-ruby itself.
If approved, TODO outside this PR before merge:
> chore: promote Robb Kidd to Approver

- instrumentation/pg/README.md
- instrumentation/pg/lib/opentelemetry/instrumentation/pg.rb
- instrumentation/pg/lib/opentelemetry/instrumentation/pg/patches/connection.rb
- instrumentation/pg/test/opentelemetry/instrumentation/pg/instrumentation_test.rb
Adding the `with_attributes` feature to PG instrumentation (e.g. mysql2: https://github.com/open-telemetry/opentelemetry-ruby/pull/1175)
This is going to be the forth one (we already have this feature in `Redis`, `HTTP::ClientContext` and `mysql2`) so still under the threshold of duplication 😄 : https://github.com/open-telemetry/opentelemetry-ruby/pull/1157#issuecomment-1089070239
https://github.com/open-telemetry/opentelemetry-ruby/discussions/1341
> feat: Add `with_attributes` context propagation for PG instrumentation

- instrumentation/action_pack/lib/opentelemetry/instrumentation/action_pack/patches/action_controller/metal.rb
- instrumentation/action_pack/test/opentelemetry/instrumentation/action_pack/patches/action_controller/metal_test.rb
- instrumentation/action_pack/test/test_helpers/controllers/example_controller.rb
- instrumentation/action_pack/test/test_helpers/routes.rb
The current implementation for the `enable_recognize_route` option will add the last of all matching routes to the `http.route` span attribute. In our experience, this has not been the correct route and we see all traces with a `http.route` of `/`. This fix sets the value based the longest match, rather than the last, which is working for us.
Update: To clarify the routing scenario this fix addresses, we have mounted rails engines on `/` and from further testing in our app it's _these_ routes that are being matched and turning up last in the order of matched routes and results in an incorrect value for `http.route`.
> Ensures the correct route is add to http.route span attribute

- instrumentation/mongo/README.md
- instrumentation/mongo/lib/opentelemetry/instrumentation/mongo/command_serializer.rb
- instrumentation/mongo/lib/opentelemetry/instrumentation/mongo/instrumentation.rb
- instrumentation/mongo/lib/opentelemetry/instrumentation/mongo/subscriber.rb
- instrumentation/mongo/test/opentelemetry/instrumentation/mongo/subscriber_test.rb
Other Ruby instrumentation (e.g. Redis) support three db statement modes: omit, include and obfuscate. Currently, the include mode behaves like obfuscate. The change isn't backwards compatible (in case someone explicitly used "include"), but it's consistent with other instrumentations. Also, the current state is misleading as I'd expect "include" not to do anything with the statement
> feat: support mongodb db statement without obfuscation

- instrumentation/redis/lib/opentelemetry/instrumentation/redis/instrumentation.rb
- instrumentation/redis/lib/opentelemetry/instrumentation/redis/middlewares/redis_client.rb
- instrumentation/redis/lib/opentelemetry/instrumentation/redis/patches/redis_v4_client.rb
- instrumentation/redis/opentelemetry-instrumentation-redis.gemspec
- instrumentation/redis/test/opentelemetry/instrumentation/redis/instrumentation_test.rb
- instrumentation/redis/test/opentelemetry/instrumentation/redis_client_test.rb
- instrumentation/redis/test/test_helper.rb
redis-rb 5.0 ditched its internal client and now simply delegate to the `redis-client` gem.
@fbogsany @robertlaurin
> redis-rb 5.0 and redis-client support

- .github/actions/test_gem/action.yml
A change in `ruby@3.1`, `rubygems`, and/or `bundler@2.3.23` is preventing native extensions both `sqlite3` and `nokogiri` on Windows.
I tried a few different incantations to force bundler to load platform specific versions of [`x64-mingw-ucrt`](https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/138), however all attempts fell short in some way.
Locking the bundler version to 2.3.22 was the only way I could get the native extensions to install.
This is a temporary fix until we can figure out what changed in the bundler ecosystem to cause this issue.
cc: @johnnyshields
> fix: Windows Ruby 3.1 Native Extensions Installs

- .github/actions/test_gem/action.yml
- .github/workflows/ci.yml
Shortening the names makes them easier to read: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/140/checks
> chore: Shorten GH Action Build Names

- .github/actions/test_gem/action.yml
- .github/workflows/ci.yml
The `set-output` command is being deprecated, and so we need to migrate.
Per the guides, this looks like the easiest replacement.
Fixes #144
> ci: replace newly-deprecated commands in actions

- instrumentation/action_pack/lib/opentelemetry/instrumentation/action_pack/instrumentation.rb
- instrumentation/action_pack/test/opentelemetry/instrumentation/action_pack/patches/action_controller/metal_test.rb
The `span_naming` option is not declared in `OpenTelemetry::Instrumentation::ActionPack::Instrumentation`, so this option is ignored if the class is configured using `OpenTelemetry::SDK.configure` method.
The `span_naming` is validated against 2 values: `:controller_action` and `:rails_route` and the default value is `:rails_route`.
> fix: declare span_naming option in action_pack instrumentation

- instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2/patches/client.rb
- instrumentation/mysql2/test/opentelemetry/instrumentation/mysql2/instrumentation_test.rb
😭 
```
ArgumentError: invalid byte sequence in UTF-8
gems/opentelemetry-instrumentation-mysql2-0.21.0/lib/opentelemetry/instrumentation/mysql2/patches/client.rb:76 gsub	
gems/opentelemetry-instrumentation-mysql2-0.21.0/lib/opentelemetry/instrumentation/mysql2/patches/client.rb:76 obfuscate_sql	
gems/opentelemetry-instrumentation-mysql2-0.21.0/lib/opentelemetry/instrumentation/mysql2/patches/client.rb:59 query
```
> fix: handle encoding errors in mysql obfuscation

- instrumentation/rails/test/instrumentation/opentelemetry/instrumentation/rails/patches/action_controller/metal_test.rb
* ActionPack instrumentation now defaults enabled_recognize_route to true, and this means the http.route is added by default.
* This also corrects the tests description and adds the code.namspace and code.function attributes
--- 
https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/170 was merged while tests were failing and this addresses the failures on `main`
Sorry about that, it wasn't clear to me that the tests were failing in a different gem than I made the changes in. I missed that totally.
---
The rails tests in the rails gem are very minimal, is this expected? https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/rails/test/instrumentation/opentelemetry/instrumentation/rails/patches/action_controller/metal_test.rb
The ActionPack tests …
> test: Fix Rails tests for new ActionPack instrumentation default behaviour

- instrumentation/sinatra/opentelemetry-instrumentation-sinatra.gemspec
Right now, Sinatra accepts anything in the `0.21.x` series. I think we should allow it to accept anything in the `0.x` series. Per Semver.org, this will allow us to add backwards-compatible functionality to rack instrumentation (as in #197) without explicitly bumping Sinatra's dep:
> Given a version number MAJOR.MINOR.PATCH, increment the:
> MAJOR version when you make incompatible API changes
> MINOR version when you add functionality in a backwards compatible manner
> PATCH version when you make backwards compatible bug fixes
> Loosen Sinatra's dependency on rack instrumentation

- instrumentation/action_pack/opentelemetry-instrumentation-action_pack.gemspec
Right now, actionpack instrumentation accepts any rack instrumentation release in the 0.21.x series. I think we should allow it to accept anything in the 0.x series. Per Semver.org, this will allow us to add backwards-compatible functionality to rack instrumentation (as in https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/197) without explicitly bumping actionpack's dep:
> Given a version number MAJOR.MINOR.PATCH, increment the:
> MAJOR version when you make incompatible API changes
> MINOR version when you add functionality in a backwards compatible manner
> PATCH version when you make backwards compatible bug fixes
(companion to https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/198)
> Loosen actionpack dep on rack instrumentation

- instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/utils.rb
I recently got pulled on a memcached performance issue, we were seeing horribly slow memcached operations.
After profiling it turns out that 99% of the time was spent in opentelemetry.
This was particularly bad when the payload we were writing in memcache was a large (1MB) binary blob.
benchmark:
```ruby
require 'bundler/inline'
gemfile do
source 'https://rubygems.org'
gem 'opentelemetry-instrumentation-dalli'
gem 'benchmark-ips'
end
require 'benchmark/ips'
require 'opentelemetry-instrumentation-dalli'
require 'opentelemetry/instrumentation/dalli/utils'
operation = :set
args = ["foo", Random.bytes(1_000_000), 0, 0, nil].freeze
ORIG = OpenTelemetry::Instrumentation::Utils
module Opt
extend self
CMD_MAX_LEN = 500
def format_command(operation, args)
placeholder = "#{operation} BLOB …
```
> Fix `format_command`'s terrible performance

- .github/workflows/ci-contrib-canary.yml
- .github/workflows/ci-contrib.yml
- .github/workflows/ci-instrumentation-canary.yml
- .github/workflows/ci-instrumentation-with-services-canary.yml
- .github/workflows/ci-instrumentation-with-services.yml
- .github/workflows/ci-instrumentation.yml
JRuby 9.4.0.0 - along with amazing new MRI 3.1 compatibility - seems to
be shipping also with exotic new bugs. We're going to temporarily pin to
an older version until we have time to understand those bugs and/or help
fix them upstream (and/or help upstream fix them!).
> ci: pin to last known good jruby release

- instrumentation/pg/Appraisals
- instrumentation/pg/lib/opentelemetry/instrumentation/pg/patches/connection.rb
- instrumentation/pg/test/opentelemetry/instrumentation/pg/instrumentation_test.rb
As discovered and addressed in #142, the `pg` gem and its underlying `libpq` library allow multiple hosts and network addresses in the connection string. The solution applied there, however, does not always return accurate information about the connected peer.
When there are multiple hosts or addresses, the library [tries each in order until one succeeds](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-MULTIPLE-HOSTS). The [`target_session_attrs`](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-TARGET-SESSION-ATTRS) setting allows both primary and replica servers to be specified in the connection string, and the library will figure which is which. Always using the first value in the connection string ignores this stuff.
I don't see an explanation …
> fix: Use attributes from the active PG connection

- instrumentation/action_pack/README.md
- instrumentation/action_pack/lib/opentelemetry/instrumentation/action_pack/instrumentation.rb
- instrumentation/action_pack/lib/opentelemetry/instrumentation/action_pack/patches/action_controller/metal.rb
- instrumentation/action_pack/test/opentelemetry/instrumentation/action_pack/patches/action_controller/metal_test.rb
- instrumentation/rails/test/instrumentation/opentelemetry/instrumentation/rails/patches/action_controller/metal_test.rb
`recognize_route` can end up mutating the request object in the event it
processes a potential match that is not anchored. That is, shall we say,
not ideal. (And causes production applications to break).
I was initially going to just default the options to `off`
(essentially), but why leave potentially dangerous code lying about?
Also, it ended up being easier to just yank stuff out rather than fix
the test cases to handle the inverse of what the expected, etc. So, this
commit just removes it all.
Step backwards in convenience, sure. Big step forward in safety? Definitely.
For context: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/123/files#r1035711863
> fix!: remove enable_recognize_route and span_naming options

- instrumentation/net_http/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb
- instrumentation/net_http/test/opentelemetry/instrumentation/net/http/instrumentation_test.rb
We are observing that the Net::HTTP connect instrumentation does not respect untraced hosts.
I think this check should have been included in #108 but let me know if not having the check is intentional
> fix: add untraced check to the Net::HTTP connect instrumentation

- instrumentation/action_pack/lib/opentelemetry/instrumentation/action_pack/patches/action_controller/metal.rb
- instrumentation/action_pack/test/opentelemetry/instrumentation/action_pack/patches/action_controller/metal_test.rb
- instrumentation/action_pack/test/test_helpers/routes.rb
Some times these come through as symbols, for example when using Devise's `FailureApp`, the name will be `:respond`. So we'll String-ify the value before sending it on.
> String-ify the code.function Span attribute

- instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2/instrumentation.rb
- instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2/patches/client.rb
- instrumentation/mysql2/test/opentelemetry/instrumentation/mysql2/instrumentation_test.rb
This adds a configuration option for MySQL instrumentation to control the span name. At present, we default to expensive client-side parsing of the expression to determine the statement type, however this is contrary to recommendations in the Semantic Conventions.
This adds 3 options, defaulting to the current behaviour: `statement_type`, `db_name` and `db_operation_and_name`. The `db_name` option extracts the database name from the `query_options`, if available. The `db_operation_and_name` option additionally looks for `db.operation` in the `OpenTelemetry::Instrumentation::Mysql2.attributes` (from the current context). This allows callers to add `db.operation` to the context, if they know it.
In all cases, if no useful span name can be determined, we default to `mysql`.
> feat: add option to configure span name

- instrumentation/graphql/Appraisals
- instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/instrumentation.rb
- instrumentation/graphql/opentelemetry-instrumentation-graphql.gemspec
- instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_tracer_test.rb
Adds appraisals and constraint checks for versions between 1.9-2.0
Fixes https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/253
Removes deprecation warnings:
```console
GraphQL::Execution::Interpreter is now the default; remove `use GraphQL::Execution::Interpreter` from the schema definition (/Users/arielvalentin/github/opentelemetry-ruby-contrib/instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_tracer_test.rb:240:in `<class:SomeOtherGraphQLAppSchema>')
GraphQL::Analysis::AST is now the default; remove `use GraphQL::Analysis::AST` from the schema definition (/Users/arielvalentin/github/opentelemetry-ruby-contrib/instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_tracer_test.rb:241:in `<class:SomeOtherGraphQLAppSchema>') …
```
> chore: Add GraphQL 2.x support

- .rubocop.yml
merged Rubocop rules that were already enabled
> chore: fix bad merges

- .rubocop.yml
- instrumentation/pg/lib/opentelemetry/instrumentation/pg/patches/connection.rb
https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/CollectionCompact
> fix: Reduce Hash Allocations in PG Instrumentation

- .github/dependabot.yml
Dependabot does not support subdirectories and I did not want to bother with scripting the output:
- https://github.com/dependabot/dependabot-core/issues/2178
Dependabot does not support YAML aliases:
- https://github.com/dependabot/dependabot-core/issues/1582
> chore: Enable dependabot

- instrumentation/graphql/README.md
- instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/instrumentation.rb
- instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/tracers/graphql_tracer.rb
- instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_tracer_test.rb
For the GraphQL integration, this:
- introduces new attributes to existing platform spans
- seeks to normalize platform span names for easier identification and future aggregation
Builds on https://github.com/open-telemetry/opentelemetry-specification/pull/2456 and work done in [opentelemetry-js-contrib](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/79b2d3ff08904ce84c6bc48427cd98906c2f0d79/plugins/node/opentelemetry-instrumentation-graphql/src/utils.ts#L125-L129)
There are some differences between the GraphQL implementations in different languages that may make it harder to have globally consistent names without working with the library authors. For example, `graphql-ruby` separates out reporting of lazy (delayed, possibly async) work from its sync work, resulting in …
> Normalize GraphQL span names for easier aggregation analysis

- instrumentation/sinatra/lib/opentelemetry/instrumentation/sinatra/middlewares/tracer_middleware.rb
Fixes https://github.com/open-telemetry/opentelemetry-ruby/issues/1420
Needs tests, I would like tips on if that would be required since afaict there aren't tests for this type of guard code. Thanks!
> Check if env['sinatra.error'] exists before recording it

- instrumentation/resque/test/opentelemetry/instrumentation/resque/patches/resque_job_test.rb
It seems that _sometimes_ Resque jobs are not processed fast enough during tests; so that calling `work_off_jobs` returns another job than expected.
This PR makes sure the job queue is cleared before starting another tests; hence only the expected job will be returned, which resolves the flaky tests.
Unblocks: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/117
> fix: fix flaky tests for resque.

- instrumentation/sinatra/lib/opentelemetry/instrumentation/sinatra/middlewares/tracer_middleware.rb
- instrumentation/sinatra/test/opentelemetry/instrumentation/sinatra_test.rb
Fixes https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/292
Wait, we're *deleting* code? YUP!
tl;dr: The Rack instrumentation already catches exceptions, adds the data to the current span and marks the error status on it. 
The primary problem is if an exception is raised in `@app.call(env)`, `response` would be nil, so the error checking code in `trace_response` will throw a new exception for trying to use `response`. That *new* exception is then caught by the Rack instrumentation (I believe, or higher level instrumentation that I found when debugging). 
So, if we were to make this work and catch exceptions, record them and then raise it again (as we should since this is middleware and we don't want to interfere with other exception handling), the higher level OTEL …
> Fix incorrect error type being recorded when Sinatra route raises exception

- instrumentation/sinatra/lib/opentelemetry/instrumentation/sinatra/middlewares/tracer_middleware.rb
- instrumentation/sinatra/test/opentelemetry/instrumentation/sinatra_test.rb
This will essentially revert https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/317 , but adds a guard clause since unhandled exceptions in Sinatra will return `response = nil`.
I've tried to check if I could add the exception event in the Rack middleware; but the Sinatra exception is not available there.
@rdoherty-fastly since your tests pass, I believe it's OK. Nevertheless I would love your :eyes: on this as well.
Fixes: https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/327
> fix: add exceptions to sinatra spans, ruboproof test.

- instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/patches/active_job_callbacks.rb
- instrumentation/active_job/test/instrumentation/active_job/patches/active_job_callbacks_test.rb
Some instrumentations like the one for Sidekiq or DelayedJob, use their own id as the value for `messaging.message_id` while the spans produced by active job instrumentation use the `job.job_id` UUID.
Examples:
- Que: https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/6e89c92f189bc6e187da06ea2af4e38531b93601/instrumentation/que/lib/opentelemetry/instrumentation/que/patches/que_job.rb#L78
- DelayedJob: https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/8f40eda20e0257bc740508b4b50758285d93e895/instrumentation/delayed_job/lib/opentelemetry/instrumentation/delayed_job/plugins/tracer_plugin.rb#L37
- Sidekiq: https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/a11d8b135d9ac4c28521619dc3b4744692ae2e6e/instrumentation/sidekiq/lib/opentelemetry/instrument …
> ActiveJob instrumentation:  Adds ActiveJob::Core `provider_job_id` attribute

- instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2/patches/client.rb
- instrumentation/mysql2/test/opentelemetry/instrumentation/mysql2/instrumentation_test.rb
- instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/patches/client.rb
- instrumentation/trilogy/test/opentelemetry/instrumentation/trilogy/instrumentation_test.rb
Shopify is planning to start migrating apps from Mysql2 to Trilogy as a SQL database client. Ensuring parity between OpenTelemetry instrumentation for Mysql2 and Trilogy is important before we move to Trilogy.
This PR ensures that invalid byte sequences are handled appropriately when obfuscating SQL, taking inspiration from https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/160. I also added some additional tests to the Trilogy spec around configuring `db_statement` via an environment variable.
I noticed the Mysql2 test around invalid byte encoding was removed in https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/265 when the `enable_sql_obfuscation` config went away, and I'm not sure if that was intentional. I've added a test to the Mysql2 spec to ensure …
> fix: Ensure encoding errors handled during SQL obfuscation for Trilogy

- .github/actions/test_gem/action.yml
Using `v1` will always use the latest untested commit on `main`. Hopefully this will provide more stability to CI going forward.
> ci: Pin setup-ruby action to stable release version

- instrumentation/rack/lib/opentelemetry/instrumentation/rack/instrumentation.rb
- instrumentation/rack/opentelemetry-instrumentation-rack.gemspec
- instrumentation/rack/test/opentelemetry/instrumentation/rack/instrumentation_test.rb
- instrumentation/rack/test/test_helper.rb
This configuration option sets a rack environment variable that isn't used in the instrumentation or its dependencies.
dd-trace-rb used this option to set the span name to the Rack application Name:
https://github.com/DataDog/dd-trace-rb/blob/d76de947d66fe50f5ac6c7a6016ebbfa5c0de986/lib/datadog/tracing/contrib/rack/middlewares.rb#L158
It looks like some of the functionality was ported over but applying it to the span name was never completed:
https://github.com/open-telemetry/opentelemetry-ruby/pull/166
> feat!: Remove retain_middleware_names Rack Option

- instrumentation/trilogy/README.md
- instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy.rb
- instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/patches/client.rb
- instrumentation/trilogy/test/opentelemetry/instrumentation/trilogy/instrumentation_test.rb
Attempting to reach feature parity between Mysql2 instrumentation and Trilogy instrumentation. I believe we'll want to make additional attributes available to Trilogy spans as with Mysql2 spans.
> feat: add with_attributes context propagation to Trilogy instrumentation

- instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/instrumentation.rb
- instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/patches/client.rb
- instrumentation/trilogy/test/opentelemetry/instrumentation/trilogy/instrumentation_test.rb
Dependent on: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/347
Shopify is planning to start migrating apps from Mysql2 to Trilogy as a SQL database client. Ensuring parity between OpenTelemetry instrumentation for Mysql2 and Trilogy is important before we move to Trilogy.
This PR adds configurable span names to the Trilogy instrumentation.
> feat: add option to configure span name for trilogy

- .github/actions/test_gem/action.yml
It is sometimes difficult to debug the CI test suite because it lacks enough details to reproduce the error.
This change adds a few more details to help track down issues so we are able to reproduce them locally.
> ci: Add gem test details

- instrumentation/graphql/Appraisals
- instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/instrumentation.rb
- instrumentation/graphql/opentelemetry-instrumentation-graphql.gemspec
2.0.18 introduces a refactoring of the GraphQL Trace API that makes it incompatible with the OTel Instrumentation.
This change locks the existing implementation to lower than 2.0.18
See https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/374 See https://github.com/rmosolgo/graphql-ruby/issues/4380
> fix!: Lock graphql max version to 2.0.17

- instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2/patches/client.rb
Unsure if you want the references to include the full module name or not. eg. `SemanticConventions::Trace::DB_STATEMENT` vs `OpenTelemetry::SemanticConventions::Trace::DB_STATEMENT`, as I tried to see if there was an convention in the repository, but it seems to be mismatched [[1](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/95707f9ce9fb1a485fd7437c313615bb66dc1ffc/instrumentation/action_pack/lib/opentelemetry/instrumentation/action_pack/patches/action_controller/metal.rb#L20-L21)] [[2](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/95707f9ce9fb1a485fd7437c313615bb66dc1ffc/instrumentation/aws_sdk/lib/opentelemetry/instrumentation/aws_sdk/messaging_helper.rb#L32-L35)].
> refactor: use semantic calls in the mysql2 instrumentation

- instrumentation/rack/test/opentelemetry/instrumentation/rack/instrumentation_test.rb
In this test, we are asserting that the instrumentation is _not_
installed when the `Rack` constant is not present (see the `before`
block for this test case). We then go on to test that the configuration
is the "default" configuration that you'd get with a fresh installation.
The problem is that if the `Rack` constant is not present, then the
`instrumentation-base` code that sets all the defaults for our options
is never run (and logically, why would it?). So these test lines can
never actually succeed.
Unless, of course, the `instrumentation` object we're referring to is
_not_ a pristine, new object. And in fact, depending on what order the
tests run in, our object is _not_ a pristine, new object. If you run
basically any _other_ test in this suite before, then we actually end up …
> ci: do not test a config that will never succeed

- instrumentation/racecar/lib/opentelemetry/instrumentation/racecar/process_message_subscriber.rb
- instrumentation/racecar/test/opentelemetry/instrumentation/racecar_test.rb
- instrumentation/rdkafka/lib/opentelemetry/instrumentation/rdkafka/patches/consumer.rb
- instrumentation/rdkafka/test/opentelemetry/instrumentation/rdkafka/patches/consumer_test.rb
This PR applies a fix to rdkafka and racecar instrumentations that was previously applied to the ruby Kafka instrumentation: https://github.com/open-telemetry/opentelemetry-ruby/pull/1059
The instrumentation was assuming that message keys are only
valid utf8 strings, but message keys can be any string of bytes. See:
https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Responses
This was causing encoding errors in exporters, and lost spans, when they were trying to encode strings into utf8 before transport. These problems were originally described here: https://github.com/open-telemetry/opentelemetry-ruby/issues/751
This fix, as with ruby-kaka, skips recording Kafka message keys that are not encodable as utf-8 strings.
> fix: skip recording non-utf8 kafka keys in racecar and rdkafka

- instrumentation/rspec/README.md
This should be an uppercase S in order for the example to run properly.
> docs: Fix typo in rspec example

- instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/middlewares/client/tracer_middleware.rb
- instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/middlewares/server/tracer_middleware.rb
- instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/patches/launcher.rb
- instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/patches/poller.rb
- instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/patches/processor.rb
simple change to use semantic names over strings, will slowly make my way through the different instrumentations when I have time
> refactor: use semantic calls in the sidekiq instrumentation

- instrumentation/base/opentelemetry-instrumentation-base.gemspec
- propagator/ottrace/opentelemetry-propagator-ottrace.gemspec
- propagator/xray/opentelemetry-propagator-xray.gemspec
- resource_detectors/opentelemetry-resource_detectors.gemspec
Combining:
* #430 
* #431 
* #432 
* #433 
Updates the requirements on [rubocop](https://github.com/rubocop/rubocop) to permit the latest version.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/rubocop/rubocop/releases">rubocop's releases</a>.</em></p>
<blockquote>
<h2>RuboCop 1.50.2</h2>
<h3>Bug fixes</h3>
<ul>
<li><a href="https://redirect.github.com/rubocop/rubocop/pull/11799">#11799</a>: Fix a false positive for <code>Style/CollectionCompact</code> when using <code>reject</code> on hash to reject nils in Ruby 2.3 analysis. (<a href="https://github.com/koic"><code>@​koic</code></a>)</li>
<li><a href="https://redirect.github.com/rubocop/rubocop/issues/11792">#11792</a>: Fix an error for <code>Lint/DuplicateMatchPattern</code> when using hash …
> chore(deps-dev): update rubocop requirement from ~> 1.49.0 to ~> 1.50.2 in multiple gems

- instrumentation/grape/lib/opentelemetry/instrumentation/grape/event_handler.rb
- instrumentation/grape/test/opentelemetry/instrumentation/grape_test.rb
While testing our services with the Grape instrumentation, in some cases I ran into this error:
```
{"error"=>{"code"=>"internal_server_error", "message"=>"undefined method `name' for #<Proc:0x00007f3956ae2d38 /app/app/controllers/api/defaults.rb:20 (lambda)>\n\n            basename = formatter.name.split('::').last\n                                ^^^^^"}}
```
This happens whenever a custom Grape formatter is defined as a proc, as shown [here in the Grape docs](https://github.com/ruby-grape/grape/blob/master/README.md?plain=1#L3038).
This PR intends to fix the issue by setting the `grape.formatter.type` to 'custom' for all custom formatters (i.e. both custom classes and procs), and only keep the original formatter name for the Grape built-in formatters.
> fix: Set grape.formatter.type to 'custom' for non-Grape formatters

- instrumentation/grape/lib/opentelemetry/instrumentation/grape/event_handler.rb
- instrumentation/grape/opentelemetry-instrumentation-grape.gemspec
and remove rack as a development dependency since we already have it as a transitive dependency from grape.
> fix: remove redundant require statement for 'rack' from grape instrumentation

- instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/patches/server.rb
- instrumentation/dalli/test/opentelemetry/instrumentation/dalli/instrumentation_test.rb
What it says on the tin, addresses https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/209
> feat: add db.operation attribute for dalli

- instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/instrumentation.rb
- instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/tracers/graphql_trace.rb
Fixes #481
The `legacy_tracing_requirement_satisfied?` logic was returning `true` for `2.0.22` which meant that the tests were _never_ being in non-legacy mode which was hiding many bugs.
This updates the logic to be strict on matching `2.0.19` which will properly detect `2.0.22` as a non-legacy version now.
> fix: GraphQL tracing

- instrumentation/trilogy/Appraisals
- instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/instrumentation.rb
- instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/patches/client.rb
- instrumentation/trilogy/test/opentelemetry/instrumentation/trilogy/instrumentation_test.rb
Add `DB_NAME` to the default attributes for the Trilogy instrumentation. 
This follows the `mysql2` instrumentation: https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2/patches/client.rb#L137
> feat!: Add database name for trilogy traces

- instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/patches/client.rb
- instrumentation/trilogy/test/opentelemetry/instrumentation/trilogy/instrumentation_test.rb
MySQL server instances have a logical host name and an instance node names.
This is particularly useful when running in clustered mode where a logical hostname is used to connect to a cluster but you also want to record what specific node is executing your query.
Trilogy exposes the instance node name via `@connected_host` as well as the configured `host` name in its `connection_options`.
This breaking change ensures that the `net.peer.name` is always set to the logical host name, while the individual instance name is being recorded in a separate attribute.
cc: @cschleiden
> feat!: Separate logical MySQL host from connected host

- instrumentation/rack/lib/opentelemetry/instrumentation/rack/instrumentation.rb
Fixes https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/518
When attempting to use the Rack Events Handler via ActionPack, the install process raises the following error:
```ruby
Failure/Error: Rails.application.initialize!
NameError:
uninitialized constant OpenTelemetry::Instrumentation::Rack::Middlewares::EventHandler
[::Rack::Events, [OpenTelemetry::Instrumentation::Rack::Middlewares::EventHandler.new]]
^^^^^^^^^^^^^^
```
This is due to constant value shadowing occurring in the instrumentation namespace, where the defined check in require_dependencies is not searching the root namespace and is instead searching the OpenTelemetry::Instrumentation::Rack namespace:
```ruby
Rack::Events
(ruby) defined?(Rack::Events)
nil
(ruby) defined?(::Rack::Events)
"constant"
```
This …
> fix: Ensure Rack Events Handler Exists

- instrumentation/dalli/opentelemetry-instrumentation-dalli.gemspec
- instrumentation/ethon/opentelemetry-instrumentation-ethon.gemspec
- instrumentation/excon/opentelemetry-instrumentation-excon.gemspec
- instrumentation/faraday/opentelemetry-instrumentation-faraday.gemspec
- instrumentation/http_client/opentelemetry-instrumentation-http_client.gemspec
- instrumentation/koala/opentelemetry-instrumentation-koala.gemspec
- instrumentation/net_http/opentelemetry-instrumentation-net_http.gemspec
- instrumentation/rack/opentelemetry-instrumentation-rack.gemspec
- instrumentation/rdkafka/opentelemetry-instrumentation-rdkafka.gemspec
- instrumentation/redis/opentelemetry-instrumentation-redis.gemspec
- instrumentation/restclient/opentelemetry-instrumentation-restclient.gemspec
- instrumentation/sidekiq/opentelemetry-instrumentation-sidekiq.gemspec
- instrumentation/sinatra/opentelemetry-instrumentation-sinatra.gemspec
Common bumped minor when it dropped Ruby 2.7 support. Instrumentation had already dropped Ruby support < 3.0, so this is a patch change to allow instrumentation to coexist with newer -common and therefore also coexist with newer -sdk that requires newer -common.
Another use of Budget Dependabot:
```bash
❯ git ls-files \*.gemspec \
| xargs \
sed -i '' \
-E "s/'opentelemetry-common', '~> [[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+'/'opentelemetry-common', '~> 0.20.0'/"
```
Quick check:
```bash
❯ git ls-files \*.gemspec \
| xargs grep "opentelemetry-common" \
| wc -l
13
❯ git ls-files \*.gemspec \
| xargs grep "opentelemetry-common" \
| grep "0.20.0" \
| wc -l
13
```
> chore(deps): update opentelemetry-common from 0.19.3 to 0.20.0

- instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/patches/client.rb
- instrumentation/trilogy/test/opentelemetry/instrumentation/trilogy/instrumentation_test.rb
This adds `db.user` to spans generated by Trilogy instrumentation. This is a [recommended connection-level attribute](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-spans.md#connection-level-attributes). It is useful for distinguishing read-only vs writer connections, for example.
> Add db.user to Trilogy spans

- instrumentation/pg/lib/opentelemetry/instrumentation/pg/patches/connection.rb
- instrumentation/pg/test/opentelemetry/instrumentation/pg/patches/connection_test.rb
https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/570
"As a result of the fact blocks are captured by closures they cannot be passed implicitly to methods created with `define_method`; they must instead be passed explicitly using the `define_method(meth) { |args, &block| ... }` syntax."
from https://banisterfiend.wordpress.com/2010/11/06/behavior-of-yield-in-define_method/
This PR changes the "exec-ish" and "exec-prepared-ish" methods to all optionally handle an explicit block, with a new separate test file specifically for these PG::Connection patches.
This PR does not change the "prepare-ish" methods as those don't seem to return anything anyway.
> fix: Pass block explicitly in `define_method` calls for PG instrumentation query methods

- instrumentation/active_job/test/instrumentation/active_job/patches/active_job_callbacks_test.rb
- resource_detectors/test/opentelemetry/detectors/azure_test.rb
- resource_detectors/test/opentelemetry/detectors/google_cloud_platform_test.rb
Minitest 5.19 removes the automatic compatability layer that allowed users to use `MiniTest` camel case module name.
https://github.com/minitest/minitest/compare/v5.18.1...v5.19.0
Rather than continuing to support antiquated code lets bring ourselves up to date with a rename that happened almost 10 years ago.
> ci: Fix Minitest

- instrumentation/graphql/Appraisals
- instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/instrumentation.rb
- instrumentation/graphql/test/instrumentation/graphql/instrumentation_test.rb
- instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_trace_test.rb
- instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_tracer_test.rb
- instrumentation/graphql/test/test_helper.rb
Following https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/482#issuecomment-1570289103
- We're now testing each tracer implementation explicitly.
- The installation logic is being tested.
- Remove the logic that disallowed use of the legacy tracer with current releases of graphql
> fix: GraphQL tests and installation

- instrumentation/grape/opentelemetry-instrumentation-grape.gemspec
Fixes issue reported in https://cloud-native.slack.com/archives/C01NWKKMKMY/p1690982323934849
> Hi, we’ve run into an issue with the most recent opentelemetry-api release to 1.2x causing opentelemetry-instrumentation-all to be downgraded by dependabot. From what I can gather this is due to some instrumentation having dependencies of opentelemetry-api <~ 1.1 rather than opentelemetry-api <~ 1 .
> Looks like it is just the grape instrumentation from a quick check: https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-ruby-contrib+spec.add_dependency+%27opentelemetry-api%27+1.1&type=code
> fix: Fix opentelemetry-api version constraint in grape gemspec

- instrumentation/base/CHANGELOG.md
- resource_detectors/CHANGELOG.md
The auto-generated changelogs caused failures in releasing resource detectors and base
https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/611
> chore: Fix changelogs

- instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/instrumentation.rb
- instrumentation/sidekiq/test/opentelemetry/instrumentation/sidekiq/instrumentation_test.rb
- instrumentation/sidekiq/test/test_helper.rb
This change will ensure the middleware is put at the front of the Client and Server middleware chains, by default. This is a change from the existing behavior which will add them to the end of the chain, and that position is determined entirely by when the SDK is configured. In a Rails app, that usually means it depends on the name of the `config/initializers/*.rb` file `OpenTelemetry::SDK.configure` is called from.
I'm not sure if we should consider this a breaking change or not. I suppose _maybe_ as someone could have accidentally been depending on the order the middleware was kinda-sorta-randomly being installed. Thoughts?
> Ensure Sidekiq TracerMiddleware is in expected order

- instrumentation/active_record/lib/opentelemetry/instrumentation/active_record/patches/transactions_class_methods.rb
- instrumentation/active_record/test/instrumentation/active_record/patches/transactions_class_methods_test.rb
~~This ensures that if a class is dynamically instantiated (singleton class / metaclass) such as by the [Blazer](https://github.com/ankane/blazer/blob/ade703d022bc98c2bd1a1259010daab3043fd102/lib/blazer/adapters/sql_adapter.rb#L12) gem, the transaction name string is used rather than something like `#<Class:0x00007fc635f69cf0>(FooBar)`.~~
This ensures that if a class is dynamically instantiated (singleton class / metaclass) such as by the Blazer gem, the transaction name string is used for the code namespace rather than setting the span name to something like #<Class:0x00007fc635f69cf0>(FooBar)
> fix: ensure that transaction name property is used, rather than self

- instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/tracers/graphql_trace.rb
- instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_trace_test.rb
All of the graphql-ruby built-in tracers use the common [`PlatformTrace` module](https://github.com/rmosolgo/graphql-ruby/blob/15cf025a2fd34518529c95054a10d4be1985ff22/lib/graphql/tracing/platform_trace.rb). OpenTelemetry's tracer does not use it directly, but uses the same underlying instance variable and method names.
This can cause conflicts because the new tracing API mixes in trace modules into a single class. This means OpenTelemetry's trace module could override other ones (or vice versa).
This fix avoids conflicts entirely by using the `opentelemetry` prefix for some methods and instance variables instead of the ones used in `PlatformTrace`.
An alternative solution would be to refactor this implementation to actually use `PlatformTrace`. I chose against it some reason originally …
> fix: improve GraphQL tracing compatibility with other tracers

- instrumentation/active_support/lib/opentelemetry/instrumentation/active_support/span_subscriber.rb
The support subscriber was allocating multiple arrays per valid attribute combination, as well as attempted to compact the array to remove `nil` values for each invalid attribute, then converted the arrays into a hash.
This change removes the intermediate arrays and instead uses a hash to store the attributes, which means there isn't a need to compact the accumulating variable.
> perf: Reduce Object allocation

- instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/patches/active_job_callbacks.rb
- instrumentation/active_job/test/instrumentation/active_job/patches/active_job_callbacks_test.rb
- instrumentation/aws_sdk/lib/opentelemetry/instrumentation/aws_sdk/handler.rb
- instrumentation/aws_sdk/test/opentelemetry/instrumentation_test.rb
- instrumentation/bunny/lib/opentelemetry/instrumentation/bunny/patch_helpers.rb
- instrumentation/bunny/test/opentelemetry/instrumentation/bunny/patches/channel_test.rb
- instrumentation/bunny/test/opentelemetry/instrumentation/bunny/patches/consumer_test.rb
- instrumentation/bunny/test/opentelemetry/instrumentation/bunny/patches/queue_test.rb
- instrumentation/delayed_job/lib/opentelemetry/instrumentation/delayed_job/plugins/tracer_plugin.rb
- instrumentation/delayed_job/test/opentelemetry/instrumentation/delayed_job/plugins/tracer_plugin_test.rb
- instrumentation/que/lib/opentelemetry/instrumentation/que/patches/que_job.rb
- instrumentation/que/test/opentelemetry/instrumentation/que_test.rb
- instrumentation/racecar/lib/opentelemetry/instrumentation/racecar/patches/consumer.rb
- instrumentation/racecar/test/opentelemetry/instrumentation/racecar_test.rb
- instrumentation/rdkafka/lib/opentelemetry/instrumentation/rdkafka/patches/producer.rb
- instrumentation/rdkafka/test/opentelemetry/instrumentation/rdkafka/patches/consumer_test.rb
- instrumentation/rdkafka/test/opentelemetry/instrumentation/rdkafka/patches/producer_test.rb
- instrumentation/resque/lib/opentelemetry/instrumentation/resque/patches/resque_module.rb
- instrumentation/resque/test/opentelemetry/instrumentation/resque/patches/resque_test.rb
- instrumentation/ruby_kafka/lib/opentelemetry/instrumentation/ruby_kafka/patches/client.rb
- instrumentation/ruby_kafka/lib/opentelemetry/instrumentation/ruby_kafka/patches/producer.rb
- instrumentation/ruby_kafka/test/opentelemetry/instrumentation/ruby-kafka/patches/client_test.rb
- instrumentation/ruby_kafka/test/opentelemetry/instrumentation/ruby-kafka/patches/consumer_test.rb
- instrumentation/ruby_kafka/test/opentelemetry/instrumentation/ruby-kafka/patches/producer_test.rb
- instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/middlewares/client/tracer_middleware.rb
- instrumentation/sidekiq/test/opentelemetry/instrumentation/sidekiq/middlewares/client/tracer_middleware_test.rb
- instrumentation/sidekiq/test/opentelemetry/instrumentation/sidekiq/middlewares/server/tracer_middleware_test.rb
Related to https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/561
This PR renames spans related to the client-side operation of creating a job from `* send` to `* publish` in various queuing instrumentations.
The diff might seem sizeable but I believe the changes are very repetitive thus it was better to bundle it together.
> fix(instrumentation): Align messaging instrumentation operation names

- instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/tracers/graphql_trace.rb
For cases where all keys are present, create the Hash with all its keys with `{...}` instead of building it incrementally with multiple `Hash[]` calls.
It really is a micro-optimization, but `execute_field` is on the hot path.
Bench:
```ruby
require "benchmark/ips"
Benchmark.ips do |x|
x.report("[]=") do
hash = {}
hash["a"] = 1
hash["b"] = 2
hash["c"] = 3
end
x.report("{}") do
{ "a" => 1, "b" => 2, "c" => 3 }
end
x.compare
```
Result:
```
Warming up --------------------------------------
[]=  577.660k i/100ms
{}     1.438M i/100ms
Calculating -------------------------------------
[]=     5.809M (± 2.9%) i/s -     29.461M in   5.076542s
{}     15.373M (± 0.3%) i/s -     77.651M in   5.051278s
Comparison:
{}=: 15372655.4 i/s
[]:   5808733.8 i/s - 2.65x  slower
```
> Micro optimization: build Hash w/ `{}`

- instrumentation/bunny/lib/opentelemetry/instrumentation/bunny/patch_helpers.rb
- instrumentation/bunny/test/opentelemetry/instrumentation/bunny/patch_helpers_test.rb
- instrumentation/bunny/test/test_helper.rb
bunny instrumentation errors when rabbitmq messages don't have `headers` property, e.g. published by an app that isn't instrumented yet.
```
E, [2023-09-07T12:01:06.688026 #1] ERROR -- #<Bunny::Session:0x29d88 hidden@hidden:5672, vhost=hidden, addresses=[hidden:5672]>: Uncaught exception from consumer #<Bunny::Consumer:101200 @channel_id=1 @queue=hidden @consumer_tag=hidden>: #<NoMethodError: undefined method `[]' for nil:NilClass 
carrier[key]
^^^^^> @ /gems/ruby/3.1.0/gems/opentelemetry-api-1.2.2/lib/opentelemetry/context/propagation/text_map_getter.rb:16:in `get'
```
you can reproduce the issue by spiting the [example](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/bunny/example/bunny.rb) file into a publisher without instrumentation and a …
> fix(bunny): headers property needs to exist

- CONTRIBUTING.md
I was reading the contribution guidelines (PR incoming!) and noticed a small typo, so I fixed it.
> fix: Fix "uses cases" typo in `CONTRIBUTING.md`

- instrumentation/gruf/lib/opentelemetry/instrumentation/gruf/interceptors/client.rb
- instrumentation/gruf/lib/opentelemetry/instrumentation/gruf/interceptors/server.rb
Instrumentations must not use transitive dependencies used by the library.
In this case, relying on the gruf library to load specific ActiveSupport extensions leaves the instrumentation vulnerable to bugs.
For this reason I have changed the code to use Enumerable methods instead of ActiveSupport extensions.
See https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/686
cc: @AS-AlStar
> fix: Remove dependence on activesupport

- instrumentation/delayed_job/Appraisals
- instrumentation/delayed_job/lib/opentelemetry/instrumentation/delayed_job/plugins/tracer_plugin.rb
- instrumentation/delayed_job/opentelemetry-instrumentation-delayed_job.gemspec
- instrumentation/delayed_job/test/opentelemetry/instrumentation/delayed_job/plugins/tracer_plugin_test.rb
- instrumentation/delayed_job/test/opentelemetry/instrumentation/delayed_job_test.rb
- instrumentation/delayed_job/test/test_helper.rb
The DelayedJob tests suite relied on the ActiveRecord Backend gem for testing, however incompatabilities with ActiveRecord/Rails 7.1 means would result in failures in the test suite.
It is not the responsibility of OTel Ruby Instrumentation to ensure compatability of 3rd party gems or ensure our test suite to come up with workarounds for bugs.
For this reason I have rewritten the test suite to use the Test backend that Delayed Job used to test the upstream gem.
This does introduce one change, the `created_at` attribute, which is _specific_ to the ActiveRecord backend will _no longer_ be emitted. Users that need this event should pin to earlier versions of the gem.
There is a risk here that the upstream DelayedJob gem will no longer be included in future releases, but I think that is less …
> fix!: Drop DelayedJob ActiveRecord in Tests

- instrumentation/dalli/README.md
- instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/instrumentation.rb
- instrumentation/dalli/test/opentelemetry/instrumentation/dalli/instrumentation_test.rb
- instrumentation/mysql2/README.md
- instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2/instrumentation.rb
- instrumentation/mysql2/test/opentelemetry/instrumentation/mysql2/instrumentation_test.rb
- instrumentation/pg/README.md
- instrumentation/pg/lib/opentelemetry/instrumentation/pg/instrumentation.rb
- instrumentation/pg/test/opentelemetry/instrumentation/pg/instrumentation_test.rb
Based on [opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/pull/3127) and [discussion](https://github.com/open-telemetry/opentelemetry-ruby-contrib/discussions/442), change the db.statement default sql to sanitized sql
Tested with basic test suite (e.g. `rake test`)
> feat!: obfuscation for mysql2, dalli and postgresql as default option for db_statement

- instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_trace_test.rb
- instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_tracer_test.rb
- instrumentation/graphql/test/test_helper.rb
I'm trying to address the test failures mentioned here: https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/689#issuecomment-1760704528
(Actually, I tried once already, over in https://github.com/rmosolgo/graphql-ruby/pull/4663, but I missed some failures because I was only running one of the test files.)
> Update test reset code for GraphQL-Ruby 2.1.3

- instrumentation/faraday/lib/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware.rb
- instrumentation/faraday/test/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware_test.rb
Copied from https://github.com/open-telemetry/opentelemetry-ruby/pull/1280
> Faraday uses a base URL to derive the host name which is used by the tracer middleware as the span attribute value for `net.peer.name`.
> 
> Although it seems incorrect, Faraday does not require a base URL when it is initialized and is a commonly used when using Faraday test stubs.
> 
> When the base URL is absent, the `net.peer.name` is set to `nil` triggering and invalid attribute error report and creates a bit of noise for test cases.
> 
> This change omits the `net.peer.name` attribute when it is `nil` to suppress error reporting when the host is absent.
Also, we have an app calling itself by not setting a base URL so we are observing this error in runtime.
> fix: Omit `nil` `net.peer.name` attributes

- .github/workflows/release-hook-on-closed.yml
- .github/workflows/release-hook-on-push.yml
- .github/workflows/release-perform.yml
- .github/workflows/release-request.yml
- .github/workflows/release-retry.yml
- .toys/.toys.rb
This will fix issues with incompatible version usage in configs:
https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/6534421626/job/17741560442#step:5:10
> ci: upgrade to latest stable version of toys

- instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/patches/client.rb
- instrumentation/trilogy/test/opentelemetry/instrumentation/trilogy/instrumentation_test.rb
These can be just as slow as a query if not slower.
> Trilogy: instrument connect and ping

- instrumentation/grape/lib/opentelemetry/instrumentation/grape/event_handler.rb
Addresses https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/705
I checked if we are using any other core extensions apart from `blank?` using this as a reference: https://guides.rubyonrails.org/active_support_core_extensions.html
Also, instead of replacing directly with `empty?`, I added an extra check for `nil?`. We shouldn't get `nil` values here, but I added it as a safeguard in case there are any changes in the Grape gem that change this behaviour.
Another case that was covered by `blank?` but not by `empty?` is pure whitespace strings, but I decided not to add this since it would be very unlikely to have path with whitespace.
> fix: Remove dependency on ActiveSupport core extensions from Grape instrumentation

- .github/workflows/ci-instrumentation-canary.yml
- .github/workflows/ci-instrumentation.yml
- .toys/.data/releases.yml
- instrumentation/httpx/.yardopts
- instrumentation/httpx/Appraisals
- instrumentation/httpx/CHANGELOG.md
- instrumentation/httpx/Gemfile
- instrumentation/httpx/LICENSE
- instrumentation/httpx/README.md
- instrumentation/httpx/Rakefile
- instrumentation/httpx/example/trace_demonstration.rb
- instrumentation/httpx/lib/opentelemetry-instrumentation-httpx.rb
- instrumentation/httpx/lib/opentelemetry/instrumentation.rb
- instrumentation/httpx/lib/opentelemetry/instrumentation/httpx.rb
- instrumentation/httpx/lib/opentelemetry/instrumentation/httpx/instrumentation.rb
- instrumentation/httpx/lib/opentelemetry/instrumentation/httpx/plugin.rb
- instrumentation/httpx/lib/opentelemetry/instrumentation/httpx/version.rb
- instrumentation/httpx/opentelemetry-instrumentation-httpx.gemspec
- instrumentation/httpx/test/instrumentation/httpx/instrumentation_test.rb
- instrumentation/httpx/test/instrumentation/plugin_test.rb
- instrumentation/httpx/test/test_helper.rb
[httpx](https://gitlab.com/os85/httpx) is a ruby http client.
> added httpx opentelemetry adapter

- CODEOWNERS
- instrumentation/httpx/CHANGELOG.md
The toys gem is unable to detect an initial release from a file without a header. Fixes:
https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/6762253625/job/18378001165
> chore: Fix HTTPx attribute and changelog

- instrumentation/httpx/CHANGELOG.md
- instrumentation/httpx/lib/opentelemetry/instrumentation/httpx/version.rb
This pull request prepares new gem releases for the following gems:
*  **opentelemetry-instrumentation-httpx 0.1.0** (initial release)
For each gem, this pull request modifies the gem version and provides an initial changelog entry based on [conventional commit](https://conventionalcommits.org) messages. You can edit these changes before merging, to release a different version or to alter the changelog text.
*  To confirm this release, merge this pull request, ensuring the     "release: pending" label is set. The release     script will trigger automatically on merge.
*  To abort this release, close this pull request without merging.
The generated changelog entries have been copied below:
----
* Initial Release.
> release: Release opentelemetry-instrumentation-httpx 0.1.0 (initial release)

- instrumentation/concurrent_ruby/opentelemetry-instrumentation-concurrent_ruby.gemspec
- instrumentation/ethon/opentelemetry-instrumentation-ethon.gemspec
- instrumentation/faraday/opentelemetry-instrumentation-faraday.gemspec
- instrumentation/que/opentelemetry-instrumentation-que.gemspec
- instrumentation/redis/opentelemetry-instrumentation-redis.gemspec
- instrumentation/restclient/opentelemetry-instrumentation-restclient.gemspec
- instrumentation/sidekiq/opentelemetry-instrumentation-sidekiq.gemspec
- instrumentation/sinatra/opentelemetry-instrumentation-sinatra.gemspec
Follow https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/715#issuecomment-1802893795 for more info. Currently some gems are using incompatible dev/appraisals versions which is possible only due to bug in Bundler (https://github.com/rubygems/rubygems/pull/6014). IMHO it is better to not rely on this behavour and unlock gemspec versions to be in range of Appraisals.
> Inline gemspec dev constraints with Appraisals.

- instrumentation/rack/README.md
- instrumentation/sinatra/Appraisals
- instrumentation/sinatra/README.md
Sinatra 1.x is not supported as it does not provide the Sinatra::Event API. It does not need to be appraised.
This should close #364.
This issue recommends documenting the last supported version for Sinatra 1.x, Given that the last release of Sinatra was January 2017, is this still something that is advised?
The gemspec references "sinatra", without a strict version requirement. I was going to update this but I noticed all the other instrumentation packages don't reference minimal versions for dependencies either.
> Removal Sinatra 1.x Appraisal

- instrumentation/rdkafka/CHANGELOG.md
- instrumentation/rdkafka/lib/opentelemetry/instrumentation/rdkafka/version.rb
This pull request prepares new gem releases for the following gems:
*  **opentelemetry-instrumentation-rdkafka 0.4.2** (was 0.4.1)
For each gem, this pull request modifies the gem version and provides an initial changelog entry based on [conventional commit](https://conventionalcommits.org) messages. You can edit these changes before merging, to release a different version or to alter the changelog text.
*  To confirm this release, merge this pull request, ensuring the     "release: pending" label is set. The release     script will trigger automatically on merge.
*  To abort this release, close this pull request without merging.
The generated changelog entries have been copied below:
----
* FIXED: Retry Release of 0.4.1 [#730](https://github.com/open-telemetry/opentelemetry-ruby-contrib/i …
> release: Release opentelemetry-instrumentation-rdkafka 0.4.2

- instrumentation/action_pack/example/trace_demonstration.ru
- instrumentation/action_view/example/trace_request_demonstration.ru
- instrumentation/rails/example/trace_request_demonstration.ru
While running the `trace_demonstration.ru` example in #703, I came across the following deprecation warning: 
```
DEPRECATION WARNING: `Rails.application.secrets` is deprecated in favor 
of `Rails.application.credentials` and will be removed in Rails 7.2.
```
This PR updates the references to use `credentials` instead of `secrets`.
> chore: Fix Rails 7.2 secrets deprecation warning

- README.md
Kayla and Josef are already [Ruby contrib approvers](https://github.com/orgs/open-telemetry/teams/ruby-contrib-approvers)! This brings the docs up-to-date with reality.
> update Approvers list in README

- .github/workflows/stale.yaml
Previously Stalebot marked issues as stale, but never closed them.
This PR will cause Stalebot to also close the issues after 30 days of being stale (thus a total of 60 days of no activity on the issue).
Any wrongly closed issues can always be reopened, or a new issue referencing the old issue can be created.
> chore: let stalebot close issues after 30 days of being stale.

- instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb
- instrumentation/rack/test/opentelemetry/instrumentation/rack/middlewares/tracer_middleware_test.rb
The Rack Event handler instrumentation adds a Span Event representing the time the request was enqueued. See https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/1fa08103b4bad30ff94e27ba013de390684cc029/instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/event_handler.rb#L263-L264
The older middleware-based instrumentation represents the same information (optionally enabled via `config[:record_frontend_span]`) as a `http_server.proxy` span as a "fake" parent span for the Rack server span. The Span Event approach is both more correct and more useful for analysis.
This PR "backports" the Span Event approach to the middleware instrumentation. Since this is done unconditionally in the Rack Event handler instrumentation, I've made it unconditional in the …
> fix: Backport Rack proxy event to middleware

- instrumentation/graphql/Appraisals
- instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_trace_test.rb
- instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_tracer_test.rb
- instrumentation/graphql/test/test_helper.rb
Graphql 2.2 introduces an optional C implementation of the Parser as well as optimizations to the pure Ruby parser that result in changes to what is captured during instrumentation.
Users of the pure Ruby implementation will no longer see `graphql.lex` spans emitted as a part of their traces and will instead need to switch to using the C Parser in order to explicitly see time spent in the lexer. 
This PR introduces updates to the test suite to add coverage for the C Parser and changes to the Ruby implementation. 
There are no underlying changes in the instrumentation itself.
> chore: Add Tests for GraphQL C Parser

- .github/workflows/release-hook-on-closed.yml
- .github/workflows/release-hook-on-push.yml
- .github/workflows/release-perform.yml
- .github/workflows/release-please.yaml
- .github/workflows/release-request.yml
- .github/workflows/release-retry.yml
- .github/workflows/stale.yaml
The Org Level OTel Bot Token likely a PAT, which will allow PRs opened by GH actions to trigger subsequent actions workflows.
This will fix the problem where CI jobs do not run when the bot opens a PR for release requests.
> ci: Use Org OTel Bot Token

- .github/workflows/release-hook-on-closed.yml
- .github/workflows/release-hook-on-push.yml
- .github/workflows/release-perform.yml
- .github/workflows/release-please.yaml
- .github/workflows/release-request.yml
- .github/workflows/release-retry.yml
- .github/workflows/stale.yaml
This reverts commit 586b0fb137d430e2b826f3814723dd61c8d82ff1.
It seems this is intended that the OTel Bot use forks when making changes.
> Revert "ci: Use Org OTel Bot Token (#789)"

- instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/patches/client.rb
It's possible for the `@connected_host` value to be ~unset~ `nil` because a query is made within trilogy to initially assign the `@connected_host`:
https://github.com/trilogy-libraries/trilogy/blob/3c3a3865a3896f3056b1d7c69c5244964b60937c/contrib/ruby/lib/trilogy.rb#L39-L50
This PR adds a presence check before assigning the attribute.
> Trilogy: only set `db.instance.id` attribute if there is a value

- .github/actions/test_gem/action.yml
- .github/workflows/ci-contrib-canary.yml
- .github/workflows/ci-contrib.yml
- .github/workflows/ci-instrumentation-canary.yml
- .github/workflows/ci-instrumentation-with-services-canary.yml
- .github/workflows/ci-instrumentation-with-services.yml
- .github/workflows/ci-instrumentation.yml
- .github/workflows/installation-tests.yml
- .github/workflows/release-hook-on-closed.yml
- .github/workflows/release-hook-on-push.yml
- .github/workflows/release-perform.yml
- .github/workflows/release-request.yml
- .github/workflows/release-retry.yml
- instrumentation/excon/Appraisals
- instrumentation/excon/opentelemetry-instrumentation-excon.gemspec
- instrumentation/excon/test/opentelemetry/instrumentation/excon/instrumentation_test.rb
- instrumentation/graphql/test/instrumentation/graphql/instrumentation_test.rb
Ruby 3.3 is out so this PR adds actions to test against it. 
One this to note is that `bigcommerce/gruf` does not yet support Ruby 3.3. Once https://github.com/bigcommerce/gruf/pull/197 is merged I will update the test suite to include gruf again.
> ci: Add Tests For Ruby 3.3

- CODEOWNERS
- README.md
@xuan-cao-swi has made a number of contributions to opentelemetry-ruby and opentelemetry-ruby-contrib. We'd like to promote him to contrib approver. Here is a summary of his work:
Contrib:
- [PRs authored](https://github.com/open-telemetry/opentelemetry-ruby-contrib/pulls?q=author%3Axuan-cao-swi++is%3Apr+)
- [PRs commented upon](https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues?q=commenter%3Axuan-cao-swi+) 
- [Issues opened](https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues?q=is%3Aissue+author%3Axuan-cao-swi+) 
- [Issues commented upon](https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues?q=is%3Aissue+commenter%3Axuan-cao-swi+)
Core:
- [PRs authored](https://github.com/open-telemetry/opentelemetry-ruby/pulls?q=author%3Axuan-cao-swi++is%3Ap …
> Add xuan-cao-swi to approvers

- CONTRIBUTING.md
The `bin/update-dependencies` script needs to be run within an ubuntu-linux machine. This PR updates the documentation to note this requirement.
> docs: Add note about running update-dependencies in ubuntu-linux

- README.md
Fix a broken link in "Getting Started" at README.
> fix: "Getting Started" link at README

- instrumentation/sidekiq/.yardopts
- instrumentation/sidekiq/README.md
- instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/instrumentation.rb
For users of Sidekiq instrumentation, I thought it would be nice to have a list of options and their uses.
So I added a (simple explain and format) table in the README ✏️ 
（At least no code reading required）
I improve any further explanations, items, or errors that are necessary.
If you don't need it, you can close it 🙏
> docs: ✏️ Sidekiq instrumentation options

- instrumentation/sinatra/Appraisals
- instrumentation/sinatra/opentelemetry-instrumentation-sinatra.gemspec
> chore: add appraisal for Sinatra 4.

- instrumentation/sinatra/example/Gemfile
Sinatra 4 needs `rackup` as a dependency ( [Sinatra CHANGELOG](https://github.com/sinatra/sinatra/blob/main/CHANGELOG.md) ). This PR adds it to the instrumentations example Gemfile, so the example can start.
> chore: add rackup to sinatra example Gemfile

- instrumentation/bunny/lib/opentelemetry/instrumentation/bunny/patch_helpers.rb
These disable directives silenced a warning in Rubocop 1.60.0, but the issue has been resolved on our current version, 1.60.1.
> fix: Remove disable directives leftover from older version of Rubocop

- instrumentation/resque/lib/opentelemetry/instrumentation/resque.rb
- instrumentation/resque/lib/opentelemetry/instrumentation/resque/instrumentation.rb
As formatted markdown comments on the class, the information is made visible in the Yard-generated docs without making the options appear to be class or instance variables. Possibly instrumentation READMEs could link in [the Usage section](https://github.com/open-telemetry/opentelemetry-ruby-contrib/tree/f5f21c686aa8b463a2fb6edd39260cf2a7da7043/instrumentation/resque#usage) to the instrumentation's latest version at rubydoc.info (for example, [this here resque](https://rubydoc.info/gems/opentelemetry-instrumentation-resque/OpenTelemetry/Instrumentation/Resque)) to avoid repeating the details of config options in the README but still making the options discoverable from there.
Placing all this on the Instrumentation class is in contrast to the approach used in #824 where each option has a …
> docs: relocate Resque config option comments to render in Yard docs

- .release-please-manifest.json
- helpers/mysql/lib/opentelemetry/helpers/mysql/version.rb
- helpers/sql-obfuscation/lib/opentelemetry/helpers/sql_obfuscation/version.rb
- instrumentation/mysql2/opentelemetry-instrumentation-mysql2.gemspec
- instrumentation/pg/opentelemetry-instrumentation-pg.gemspec
- instrumentation/trilogy/opentelemetry-instrumentation-trilogy.gemspec
- release-please-config.json
[The toys gem expects for initial releases to start with version `0.0.0`](https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/7817578724/job/21325809668#step:5:1116
):
```console
[2024-02-07 15:59:43  INFO]  exec: ["gh", "api", "repos/open-telemetry/opentelemetry-ruby-contrib/pulls?state=open&sort=created&direction=desc&per_page=20&head=open-telemetry:release/opentelemetry-helpers-mysql", "-H", "Accept: application/vnd.github.v3+json"]
[2024-02-07 15:59:43  INFO]  exec: ["git", "tag", "-l"]
[2024-02-07 15:59:43  INFO]  Could not find any previous releases for opentelemetry-helpers-mysql
NoMethodError: undefined method `<<' for nil:NilClass
25: /opt/hostedtoolcache/Ruby/3.0.6/x64/bin/toys:25:in `<main>'
24: /opt/hostedtoolcache/Ruby/3.0.6/x64/bin/toys:25:in `load'
23: …
```
> chore: force initial release version

- .github/workflows/release-hook-on-closed.yml
- .github/workflows/release-hook-on-push.yml
- .github/workflows/release-perform.yml
- .github/workflows/release-request.yml
- .github/workflows/release-retry.yml
- .toys/.toys.rb
This brings in several fixes including bundler failures related to the "uri" builtin gem, and the missing instance variable crash when requesting a release that includes a new gem.
> chore: Update toys and toys release script pins to 0.15.5

- instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2/patches/client.rb
- instrumentation/pg/lib/opentelemetry/instrumentation/pg/patches/connection.rb
- instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/patches/client.rb
In https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/529 a couple of `require`s were missing. This PR adds those.
Fixes: https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/858
> fix: add missing requires for sql-helpers to mysql, pg, and trilogy instrumentation

- instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/tracers/graphql_tracer.rb
- instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_tracer_test.rb
Backporting [this](https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/723) to `graphql-1.12.24`. 
Closes: https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/865 
- `graphql.field.parent` is now reporting the interface instead of the concrete class for `execute_field`. We've made this 
choice consciously in order to benefit from the very serious performance gains vs 100% accuracy. For v2, this goes back to reporting the concrete class so we always have the choice of upgrading. 
- If the `graphql.operation.name` is `nil`, we are now setting the value to `anonymous`. This allows us to detect unowned queries. 
This will result in:
- a 97% reduction in total allocated memory for this gem (130896 -> 3616) 
- a 96% reduction in total objects allocated for this gem …
> feat!: Cache GraphQL attributes

- .github/workflows/ci-instrumentation-canary.yml
- .github/workflows/ci-instrumentation.yml
- instrumentation/gruf/Appraisals
- instrumentation/gruf/lib/opentelemetry/instrumentation/gruf/version.rb
- instrumentation/gruf/opentelemetry-instrumentation-gruf.gemspec
Update appraise for gruf 2.19 and old versions
> feat: Add support gruf 2.19

- instrumentation/faraday/lib/opentelemetry/instrumentation/faraday/instrumentation.rb
- instrumentation/faraday/lib/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware.rb
- instrumentation/faraday/test/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware_test.rb
Multiple client spans are created when both Faraday and the Driver are instrumented.
This change allows for users to specify whether or not this instrumentation generates span kinds as client or internal.
This is a global configuration that effects all Faraday Connections.
> feat: faraday add support for internal spans

- instrumentation/active_record/lib/opentelemetry/instrumentation/active_record/instrumentation.rb
- instrumentation/active_record/opentelemetry-instrumentation-active_record.gemspec
Now that Ruby below 2.7 is not supported (#389, https://github.com/open-telemetry/opentelemetry-ruby-contrib/commit/38b083aa41b93bcc8f900cd65bc922c97fe26e5d) this is not needed anymore
> chore: drop dependency on ruby2_keywords

- instrumentation/faraday/lib/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware.rb
- instrumentation/faraday/test/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware_test.rb
The current `Faraday` middleware won't report `http.status_code` in
cases where an error is raised via another middleware (such as
`:raise_error` or `:json`).
This adds a special case for subclasses of `Faraday::Error` which have
response information available, so that `http.status_code` & the span
status are still added to the span.
> fix: Propagate response attributes on Faraday::Error

- instrumentation/rack/README.md
Noticed this typo whilst debugging our Rack instrumentation setup
> docs: fix typo where Rake is mentioned instead of Rack

- .github/workflows/release-please.yaml
Currently, `release-please` attempts to run on forks of opentelemetry-ruby-contrib. The workflow fails with the message "GitHub Actions is not permitted to create or approve pull requests." `release-please` is not needed on forks.
This is also the policy for the toys-based `release-hook-on-push` workflow.
I took a quick look at the other workflows and think this is the only one that needs to be ignored on forks. However, the `conventional-commits` workflow might be another good candidate.
> chore: Run release-please only on open-telemetry

- instrumentation/active_record/lib/opentelemetry/instrumentation/active_record/patches/querying.rb
Rails 7.2 (rails/rails@eabcff2) introduces the `:allow_retry` option for the `find_by_sql` method, so we need to add it to this patch to maintain compatibility. The patch doesn't use the method's args, so we can just use `(...)` to avoid this problem.
~To check the Rails version, I had to add rails as a development dependency. I added it in the gemspec and set the minimum version to 6.1 following the pattern I saw in the other libraries in this repo ([for example](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/action_pack/opentelemetry-instrumentation-action_pack.gemspec#L37)).~
> fix: instrumentation/active_record: add `:allow_retry` option to `find_by_sql` patch

- .github/workflows/conventional-commits.yaml
Dependabot creates PRs with a `chore(deps-dev):` prefix when it is updating development-only dependencies. The version of the GitHub Action we're using—`dev-build-deploy/commit-me@v1.3.1`[1]—to validate commit prefixes balks at the hyphen. `v1.4.0` includes an update[2] that recognizes scopes that contain hyphens.
[1] https://github.com/dev-build-deploy/commit-me/tree/v1.3.1
[2] https://github.com/dev-build-deploy/commit-me/commit/38d4cb09a1bf468012516a3bfbfad325f3435915
> chore(deps-ci): upgrade conventional commit check

- README.md
I'm thrilled to be [joining the opentelemetry-ruby-contrib maintainer's team!](https://cloud-native.slack.com/archives/C01NWKKMKMY/p1712247069428889) 🎉 
Here are links to some of my work:
* [Reviews](https://github.com/open-telemetry/opentelemetry-ruby-contrib/pulls?q=is%3Apr+commenter%3Akaylareopelle+-author%3Akaylareopelle) 
* [Authored PRs](https://github.com/open-telemetry/opentelemetry-ruby-contrib/pulls?q=is%3Apr+author%3Akaylareopelle+)
> chore: Move @kaylareopelle to maintainers list

- instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/tracers/graphql_trace.rb
- instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_trace_test.rb
Span names for `analyze_query` and `analyze_multiplex` were reversed and incorrect. This fixes them to be consistent with the trace hook that produces them.
> fix: analyze span names in GraphQL instrumentation

- .toys/.data/releases.yml
Follow up to #937 to make the gem releasable with our automation.
> chore: include new baggage span processor in release automation

- instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/event_handler.rb
- instrumentation/rack/test/opentelemetry/instrumentation/rack/middlewares/event_handler_test.rb
Fixes extracted baggage entries not being attached to the opentelemetry context.
> fix: rack event baggage handling

- instrumentation/dalli/opentelemetry-instrumentation-dalli.gemspec
- instrumentation/ethon/opentelemetry-instrumentation-ethon.gemspec
- instrumentation/excon/opentelemetry-instrumentation-excon.gemspec
- instrumentation/faraday/opentelemetry-instrumentation-faraday.gemspec
- instrumentation/http_client/opentelemetry-instrumentation-http_client.gemspec
- instrumentation/koala/opentelemetry-instrumentation-koala.gemspec
- instrumentation/net_http/opentelemetry-instrumentation-net_http.gemspec
- instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/event_handler.rb
- instrumentation/rack/opentelemetry-instrumentation-rack.gemspec
- instrumentation/rack/test/opentelemetry/instrumentation/rack/middlewares/event_handler_test.rb
- instrumentation/rdkafka/opentelemetry-instrumentation-rdkafka.gemspec
- instrumentation/redis/opentelemetry-instrumentation-redis.gemspec
- instrumentation/restclient/opentelemetry-instrumentation-restclient.gemspec
- instrumentation/sidekiq/opentelemetry-instrumentation-sidekiq.gemspec
- instrumentation/sinatra/opentelemetry-instrumentation-sinatra.gemspec
Depends on common 0.21.0 for https://github.com/open-telemetry/opentelemetry-ruby/pull/1634
closes: https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/962
> fix: Untrace entire request

- .github/workflows/release-please.yaml
The previous location, google-github-actions, is deprecated. All future work will be completed in googleapis.
https://github.com/google-github-actions/release-please-action?tab=readme-ov-file#migration
> chore: Update release please action to googleapis

- .github/workflows/ci-contrib.yml
The opentelemetry-propagators-vitess gem was not included in the CI. Now it will be tested along with the other propagators.
> test: Add vitess to the propagators matrix

- instrumentation/ethon/Appraisals
- instrumentation/ethon/lib/opentelemetry/instrumentation/ethon/patches/easy.rb
- instrumentation/ethon/test/opentelemetry/instrumentation/ethon/instrumentation_test.rb
The ethon instrumentation did not include the `net.peer.name` attribute like other HTTP instrumentations and was not ported from ddtrace-rb: <https://github.com/DataDog/dd-trace-rb/blob/master/lib/datadog/tracing/contrib/ethon/easy_patch.rb#L159>
This attribute is important to GitHub because we base the `peer.service` extracting the subdomain and host information from `net.peer.name`.
In order to avoid parsing the URL multiple times, I inlined the common gem `cleanse_url` function and plan to open a separate PR adding a feature to support returing URI objects instead of Strings.
> fix: Add net.peer.name to ethon

- instrumentation/grape/Gemfile
`builder` was removed as a dependency to `grape` but is used by active support in some versions.
See ruby-grape/grape#2443
See ruby-grape/grape#2445
Fixes https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/1015
> test: Fix grape test suite

- helpers/mysql/opentelemetry-helpers-mysql.gemspec
- helpers/sql-obfuscation/opentelemetry-helpers-sql-obfuscation.gemspec
- instrumentation/base/opentelemetry-instrumentation-base.gemspec
- instrumentation/dalli/opentelemetry-instrumentation-dalli.gemspec
- instrumentation/ethon/opentelemetry-instrumentation-ethon.gemspec
- instrumentation/excon/opentelemetry-instrumentation-excon.gemspec
- instrumentation/faraday/opentelemetry-instrumentation-faraday.gemspec
- instrumentation/http_client/opentelemetry-instrumentation-http_client.gemspec
- instrumentation/koala/opentelemetry-instrumentation-koala.gemspec
- instrumentation/net_http/opentelemetry-instrumentation-net_http.gemspec
- instrumentation/rack/opentelemetry-instrumentation-rack.gemspec
- instrumentation/rdkafka/opentelemetry-instrumentation-rdkafka.gemspec
- instrumentation/redis/opentelemetry-instrumentation-redis.gemspec
- instrumentation/restclient/opentelemetry-instrumentation-restclient.gemspec
- instrumentation/sidekiq/opentelemetry-instrumentation-sidekiq.gemspec
- instrumentation/sinatra/opentelemetry-instrumentation-sinatra.gemspec
Rolling out changes to opentelemetry-common is made difficult because many of the instrumentation gems that rely on it have to all receive minor version bumps.
Relaxing constraints allows for individual instrumentations to be able to use new features in the common gem without requiring a minor dependency bump of unrelated instrumentations that share that dependency.
> fix: Relax otel common gem constraints

- docker-compose.yml
- processor/baggage/README.md
- processor/baggage/lib/opentelemetry/processor/baggage/baggage_span_processor.rb
- processor/baggage/test/opentelemetry/processor/baggage/baggage_span_processor_test.rb
- Closes #956 
- Add baggage key lambda as constructor parameter to baggage span processor
- Add `ALLOW_ALL_BAGGAGE_KEYS` lambda that allows all keys
- Add unit test to verify behaviour
- Update README with examples of setting a filter
> feat!: Add baggage key predicate func to baggage span processor

- instrumentation/base/lib/opentelemetry/instrumentation/base.rb
Not sure if this is documented in some place, but adding the doc here for better clarity.
Should we add some example regarding the env var config options and also highlight the precedence (env > programmatic config) in opentelemetry.io?
> docs: add function doc for config_overrides_from_env

- instrumentation/base/CHANGELOG.md
For whatever reason the release requester added the release notes to base in the [wrong place](https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1025/files#diff-56e77db23a521227f2e9c998b52f3fd353ef19d60d294d6996159487efaf8e09). 
This change sets the release notes to the appropriate location to make the release script happy.
> chore: fix base changelog

- instrumentation/faraday/lib/opentelemetry/instrumentation/faraday/instrumentation.rb
- instrumentation/faraday/lib/opentelemetry/instrumentation/faraday/patches/connection.rb
- instrumentation/faraday/test/opentelemetry/instrumentation/faraday/middlewares/tracer_middleware_test.rb
Fixes https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/1031
Faraday >= 1 changes where the #adapter method gets called, affecting the RackBuilder patch in this gem.
Without this change, the tracer middleware gets added to the beginning of the stack instead of the end, and explicitly adding the middleware would cause it to get added twice.
This change patches `Connection#initialize` for Faraday >= 1 to preserve the behavior we had with Faraday < 1. This is similar to the dd-trace-rb change made in https://github.com/DataDog/dd-trace-rb/pull/906.
There is some followup work here to explore moving the middleware to the beginning of the stack instead of the end, but we can work on that separately.
> fix: compatibility with Faraday v1

- instrumentation/active_support/lib/opentelemetry/instrumentation/active_support/span_subscriber.rb
- instrumentation/active_support/test/opentelemetry/instrumentation/active_support/span_subscriber_test.rb
This change fixes a bug where the kind parameter was not passed along to the subscriber object
> fix: Include span kind in ActiveSupport Instrumentation helper

- instrumentation/active_job/CHANGELOG.md
- instrumentation/all/CHANGELOG.md
- instrumentation/aws_sdk/CHANGELOG.md
- instrumentation/bunny/CHANGELOG.md
- instrumentation/delayed_job/CHANGELOG.md
- instrumentation/que/CHANGELOG.md
- instrumentation/racecar/CHANGELOG.md
- instrumentation/rails/CHANGELOG.md
- instrumentation/rdkafka/CHANGELOG.md
- instrumentation/ruby_kafka/CHANGELOG.md
- instrumentation/sidekiq/CHANGELOG.md
This was actually a breaking change, and despite `:fix!` being used in the commit, the release tooling failed to mark the change as breaking.
Refs: #648, #655
> docs: Fix CHANGELOGs to reflect a past breaking change

- instrumentation/active_support/README.md
- instrumentation/active_support/lib/opentelemetry/instrumentation/active_support/span_subscriber.rb
- instrumentation/active_support/opentelemetry-instrumentation-active_support.gemspec
- instrumentation/active_support/test/opentelemetry/instrumentation/active_support/span_subscriber_test.rb
- instrumentation/active_support/test/test_helper.rb
The current implementation of ActiveSupport instrumentation sets the span name to the reverse tokenized name, e.g. `render_template.action_view` is converted to `action_view render_template`
This default behavior can sometimes seem counter intuitive for users who use ActiveSupport Notifications to instrument their own code or users who are familiar with Rails instrumentation names.
This change does a few things to address the issues listed above:
1. Uses the notification name by default as oppossed to the legacy span name
2. Allows users to provide a custom span name formatter lambda
3. Provides a proc with backward compatible span name formatter `OpenTelemetry::Instrumentation::ActiveSupport::LEGACY_NAME_FORMATTER`
See https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/95 …
> feat!: Custom ActiveSupport Span Names

- instrumentation/grape/lib/opentelemetry/instrumentation/grape/instrumentation.rb
- instrumentation/grape/test/opentelemetry/instrumentation/grape_test.rb
In some circumstances we may want to defer the installation of the rack instrumentation that is orchestrated during the grape instrumentation installation. For example, we may want to customise the installation of the rack instrumentation or we can rely on the installation being orchestrated by another framework's instrumentation (such as when Grape is mounted with Rails).
This change allows for Grape to skip the installation of the Rack instrumentation so that it can manually installed at a later time.
> feat: make the install of rack instrumentation by grape instrumentation optional

- instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/handlers.rb
- instrumentation/active_job/test/opentelemetry/instrumentation/active_job/handlers_test.rb
Fixes https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/1076
Added a basic unit test for good measure
> fix: ActiveJob::Handlers.unsubscribe

- CONTRIBUTING.md
- instrumentation/aws_lambda/README.md
- instrumentation/aws_lambda/example/trace_demonstration.rb
- instrumentation/aws_lambda/lib/opentelemetry/instrumentation/aws_lambda/handler.rb
- instrumentation/aws_lambda/test/opentelemetry/instrumentation_test.rb
The aws lambda span was not registered with context after start_span, which cause current_span can't detect it. User couldn't append attributes outside call_wrapped span. This PR attach the span to current context and detach it before finish.
> fix: register lambda span

- instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/handlers/enqueue.rb
- instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/handlers/perform.rb
- instrumentation/active_job/test/opentelemetry/instrumentation/active_job/handlers/perform_test.rb
Fixes https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/1077 as introduced at https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/677#discussion_r1686598646
Added a unit test for good measure.
> fix(active-job): Honour dynamic changes in configuration

- instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/tracers/graphql_trace.rb
- instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_trace_test.rb
Oops -- these trace modules are supposed to call `super`, where other trace modules may add instrumentation. (Calling `&block` hands control to GraphQL-Ruby, but skips other trace module code.) 
My guess is that these weren't converted to `super` when this module was migrated off of GraphQL-Ruby's own `PlatformTrace` module which worked differently (or used to have this same bug?). 
Fixes https://github.com/rmosolgo/graphql-ruby/issues/5044
TODO: 
-  ~~Along the way, I found an issue with how GraphQL::Ruby handles `GraphQL::Schema.trace_with(trace_mod)` when subclasses already exist and those subclasses have already received `.trace_with(...)` calls of their own. I'm trying to work that out in https://github.com/rmosolgo/graphql-ruby/pull/5045, but that issue is making this test fail (I …
> fix: Add super calls to GraphqlTrace

- instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/handlers.rb
- instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/handlers/default.rb
- instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/handlers/enqueue.rb
- instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/handlers/perform.rb
- instrumentation/active_job/test/opentelemetry/instrumentation/active_job/handlers/discard_test.rb
- instrumentation/active_job/test/opentelemetry/instrumentation/active_job/handlers/retry_stopped_test.rb
Designed to be merged after https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1079
Related to:
- https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/648
- https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/677
Currently, active job events are:
| Notification | Before | After |
| - | - | - |
| `enqueue.active_job` | `#{prefix} publish` | `#{prefix} publish` |
| `enqueue_at.active_job` | `#{prefix} publish` | `#{prefix} publish` |
| `enqueue_retry.active_job` | `enqueue_retry.active_job` | `#{prefix} enqueue_retry` |
| `perform.active_job` | `#{prefix} process` | `#{prefix} process` |
| `retry_stopped.active_job` | `retry_stopped.active_job` | `#{prefix} retry_stopped` |
| `discard.active_job` | `discard.active_job` | `#{prefix} discard` |
Prefix …
> feat(active-job)!: Normalize event messages

- instrumentation/base/lib/opentelemetry/instrumentation/base.rb
Closes https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/1095
When user provides the `:enabled` in config option, the value will be passed into config_options, which is not part of instrumentation options so the [L308](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/opentelemetry-instrumentation-base/v0.22.5/instrumentation/base/lib/opentelemetry/instrumentation/base.rb#L308) will appear.
> fix: fix the issue of wrong log msg

- .github/workflows/ci-contrib.yml
Now the helpers-* job within the ci-contrib action will test Ruby 3.3, like all the other actions/jobs.
> ci: Add Ruby 3.3 tests for helpers-* gems

- instrumentation/pg/Appraisals
* drop pg-1.2
* This addresses the specific pg error found in #1097.
* pg 1.2.x does not work under Ruby >= 3.0.
* We currently support and test only Ruby >= 3.0.
* add pg-1.4
* This used to be latest! Now latest in 1.5. 
With thanks to @matthewtusker for raising the issue and helping to resolve!
> fix(pg): update versions to be tested (includes drop support for pg 1.2)

- instrumentation/action_mailer/Appraisals
- instrumentation/action_pack/Appraisals
- instrumentation/action_view/Appraisals
- instrumentation/active_record/Appraisals
- instrumentation/active_support/Appraisals
- instrumentation/pg/opentelemetry-instrumentation-pg.gemspec
- instrumentation/que/Gemfile
- instrumentation/rails/Appraisals
* Rails 7.2.0 was released on August 9, 2024. Add appraisals for the new version.
* pg was installing activerecord 3.2, this sets a bottom limit of 6.1, the oldest supported version of Rails 
* que is not yet compatible with Rails 7.2, so set a constraint to install something between 6.1 and 7.1 (it will be compatible once https://github.com/que-rb/que/pull/423 is merged)
Resolves #1113 
(I had this prefixed to `chore`, but switched it to `test`, not sure if one is preferred over the other)
> test: Update Appraisals for Rails 7.2

- instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/instrumentation.rb
Otherwise, `ActiveSupport` ends up resolving to `OpenTelemetry::Instrumentation::ActiveSupport`.
`OpenTelemetry::Instrumentation::Registry#install_instrumentation` rescues the exception, so the prepend ends up being (somewhat) silently dropped.
This results in the patch not being adding, which causes `OpenTelemetry.propagation.inject(job.__otel_headers)` to raise, dropping the span
> fix(active-job): Prefix ::ActiveSupport when installing the instrumentation

- instrumentation/active_record/lib/opentelemetry/instrumentation/active_record/instrumentation.rb
Came across an error when ActiveRecord Instrumentation is being installed in a Rails app.
Use `::ActiveSupport` to look for constant in the top-level namespace.
``` 
OpenTelemetry error: Instrumentation: OpenTelemetry::Instrumentation::ActiveRecord unhandled exception during install:
...
undefined method `on_load' for OpenTelemetry::Instrumentation::ActiveSupport:Module
...
ActiveSupport.on_load(:active_record) do
^^^^^^^^
```
> fix: use ActiveSupport from top-level namespace

- instrumentation/action_view/lib/opentelemetry/instrumentation/action_view.rb
- instrumentation/action_view/lib/opentelemetry/instrumentation/action_view/instrumentation.rb
- instrumentation/action_view/lib/opentelemetry/instrumentation/action_view/railtie.rb
- instrumentation/action_view/opentelemetry-instrumentation-action_view.gemspec
This restores the functionality that was reverted 94c3c3bfafa4e78a7e153d38b5e43767144892bb.
I had originally introduced this functionality in this PR: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1039
cc: @mrsimo
> fix: ActionView Support Legacy Formats
