instrumentation/sidekiq/Rakefile

Start redis server only if it's available

---

instrumentation/all/opentelemetry-instrumentation-all.gemspec

Pull in latest [release](https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/181)

Bump rails instrumentation in -all

---

instrumentation/rdkafka/opentelemetry-instrumentation-rdkafka.gemspec

Begins fixing https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/187

Loosen rdkafka opentelemetry-api dependency

---

.github/workflows/ci-contrib-canary.yml
.github/workflows/ci-contrib.yml
.github/workflows/ci-instrumentation-canary.yml
.github/workflows/ci-instrumentation-with-services-canary.yml
.github/workflows/ci-instrumentation-with-services.yml
.github/workflows/ci-instrumentation.yml
instrumentation/net_http/test/opentelemetry/instrumentation/net/http/instrumentation_test.rb

See https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/248

chore: Upgrade to JRuby 9.4.0.0

---

.rubocop.yml

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/GlobalStdStream

chore: Enable Style/GlobalStdStream

---

.rubocop.yml
instrumentation/action_view/lib/opentelemetry/instrumentation/action_view/railtie.rb
instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_tracer_test.rb
instrumentation/rdkafka/lib/opentelemetry/instrumentation/rdkafka/patches/consumer.rb
resource_detectors/test/opentelemetry/detectors/azure_test.rb

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/LineLength

chore: Enable Layout/LineLength

---

.rubocop.yml
instrumentation/base/lib/opentelemetry/instrumentation/base.rb

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/DuplicateBranch

chore: Enable Lint/DuplicateBranch

---

.rubocop.yml
instrumentation/redis/.rubocop.yml
instrumentation/sidekiq/.rubocop.yml
resource_detectors/lib/opentelemetry/resource/detectors/google_cloud_platform.rb
resource_detectors/test/opentelemetry/detectors/google_cloud_platform_test.rb

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FetchEnvVar

chore: Enable Style/FetchEnvVar

---

.rubocop.yml
instrumentation/active_model_serializers/test/opentelemetry/instrumentation/active_model_serializers_test.rb
instrumentation/aws_sdk/test/opentelemetry/instrumentation_test.rb
instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_tracer_test.rb

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/SymbolConversion

chore: Enable Lint/SymbolConversion

---

.rubocop.yml
instrumentation/bunny/.rubocop.yml
instrumentation/graphql/.rubocop.yml
instrumentation/rspec/.rubocop.yml

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/EmptyBlock

chore: Enable Lint/EmptyBlock

---

.rubocop.yml
instrumentation/que/lib/opentelemetry/instrumentation/que/middlewares/server_middleware.rb

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/HashConversion

chore: Enable Style/HashConversion

---

.rubocop.yml
instrumentation/racecar/example/config/racecar.rb

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/RedundantFetchBlock

chore: Enable Style/RedundantFetchBlock

---

instrumentation/action_pack/CHANGELOG.md

Mention fix for code.function change

---

instrumentation/action_pack/Appraisals
instrumentation/action_pack/lib/opentelemetry/instrumentation/action_pack/instrumentation.rb
instrumentation/action_view/Appraisals
instrumentation/action_view/lib/opentelemetry/instrumentation/action_view/instrumentation.rb
instrumentation/active_job/Appraisals
instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/instrumentation.rb
instrumentation/active_job/opentelemetry-instrumentation-active_job.gemspec
instrumentation/active_record/Appraisals
instrumentation/active_record/lib/opentelemetry/instrumentation/active_record/instrumentation.rb
instrumentation/active_support/lib/opentelemetry/instrumentation/active_support/span_subscriber.rb
instrumentation/rails/Appraisals
instrumentation/rails/lib/opentelemetry/instrumentation/rails/instrumentation.rb
instrumentation/sidekiq/opentelemetry-instrumentation-sidekiq.gemspec

Closes https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/249

feat!: Drop Rails 5 Support

---

instrumentation/rails/README.md

Fixes typo on `Compatibility` -> `Compatibility`

Fix README.md typo

---

instrumentation/base/lib/opentelemetry/instrumentation/base.rb
instrumentation/rack/example/trace_demonstration3.rb
instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/event_handler.rb
instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb
instrumentation/rack/test/test_helper.rb

Rubocop Appeasement, broken up over a few commits, one commit per cop.
(I preambled this PR with "ci:" thinking that this is CI appeasement on unreleased changes, so therefore not a "fix:". Happy to be corrected on that!)

ci: (base, rack) appease rubocop after Rack events update

---

.instrumentation_generator/instrumentation_generator.rb

Small fix for a wrong line in InstrumentationGenerator

fix: InstrumentationGenerator

---

README.md

More hands on deck for merging and releasing.

Promote Robb Kidd from Approver to Maintainer

---

README.md

docs: correction to grammar in README.md

---

.github/workflows/stale.yaml

Hopefully this will help us manage stale issues and PRs

chore: Add stale bot to Issues and PRs

---

README.md

Update README.md remove shopify affiliation contrib

---

.github/workflows/stale.yaml
instrumentation/http/README.md
instrumentation/http/lib/opentelemetry/instrumentation/http/instrumentation.rb
instrumentation/http/lib/opentelemetry/instrumentation/http/patches/client.rb
instrumentation/http/test/instrumentation/http/patches/client_test.rb

- allow net::http spans to be preprocessed before sending

feat: Add span_preprocessor hook

---

Gemfile
instrumentation/base/opentelemetry-instrumentation-base.gemspec
propagator/ottrace/opentelemetry-propagator-ottrace.gemspec
propagator/xray/opentelemetry-propagator-xray.gemspec
resource_detectors/opentelemetry-resource_detectors.gemspec

pr reflects 
- https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/495
- https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/494
- https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/493
- https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/492
- https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/491

chore: Combine dependabot rubocop bumps

---

instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/tracers/graphql_trace.rb
instrumentation/graphql/test/instrumentation/graphql/tracers/graphql_tracing_test.rb

`resolve_type_lazy` was missing the `&block` argument to pass through. This also adds a test case which was hiding this bug.

fix: GraphQL resolve_type_lazy

---

.github/workflows/ci-instrumentation-with-services-canary.yml
.github/workflows/ci-instrumentation-with-services.yml

Fix spelling error in actions label

---

instrumentation/faraday/Appraisals

There's been several 1.x minor releases and a 2.x major release. Let's test against the latest minor release for each of the Faraday majors.

test: update faraday test version matrix

---

.rubocop.yml
instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/patches/active_job_callbacks.rb
instrumentation/aws_sdk/lib/opentelemetry/instrumentation/aws_sdk/handler.rb
instrumentation/base/lib/opentelemetry/instrumentation/base.rb
instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/tracers/graphql_tracer.rb
instrumentation/mysql2/lib/opentelemetry/instrumentation/mysql2/patches/client.rb
instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb
instrumentation/rack/lib/opentelemetry/instrumentation/rack/util/queue_time.rb
instrumentation/redis/lib/opentelemetry/instrumentation/redis/patches/redis_v4_client.rb
instrumentation/resque/lib/opentelemetry/instrumentation/resque/patches/resque_job.rb
instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/middlewares/server/tracer_middleware.rb
instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/patches/client.rb
releases/Gemfile
releases/Rakefile
releases/test/integration/installation_test.rb
resource_detectors/lib/opentelemetry/resource/detectors/google_cloud_platform.rb
resources/container/lib/opentelemetry/resource/detector/container.rb

In most cases these rules do not apply to instrumentations and test cases

fix: Remove inline linter rules

---

.github/workflows/stale.yaml

Close PRs 30 days instead of 15 days after a ping

chore: Update stalebot

---

instrumentation/racecar/README.md

Fixes markdown header rendering in racecar docs

fix: fix markdown header

---

Dockerfile
instrumentation/active_record/Gemfile

Attempts to fix the broken test on active_record
related to https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/939

fix: resolve active_record testing issue

---

LICENSE

See open-telemetry/community#2056 for background

fix: revert modifications to Apache license

---

.github/actions/test_gem/action.yml
.github/workflows/ci-contrib-canary.yml
.github/workflows/ci-contrib.yml
.github/workflows/ci-instrumentation-with-services.yml
.github/workflows/ci-instrumentation.yml

Update CI to run JRuby under Ruby 3.1

chore: JRuby 9.4.6.0 - Ruby 3.1

---

.github/workflows/ci-instrumentation.yml
instrumentation/action_mailer/Gemfile
instrumentation/action_mailer/lib/opentelemetry/instrumentation/action_mailer/instrumentation.rb
instrumentation/action_mailer/opentelemetry-instrumentation-action_mailer.gemspec
instrumentation/action_mailer/test/opentelemetry/instrumentation/action_mailer/instrumentation_test.rb

Missed this as part of 
https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/887

ci: Add ActionMailer CI

---

instrumentation/grape/Appraisals

Fixes https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/1005

ci: Updates grape appraisals
